In [ ]:
from pathlib import Path # Import Path so we can work with file/folder paths easily
import pandas as pd
from datetime import datetime

In [ ]:
data_file = Path('/content/team_1.parquet')
data = pd.read_parquet(data_file, engine='pyarrow') #engine='pyarrow' tells pandas which library to use to read parquet files

# We convert each text value into a real datetime object
data['timestamp'] = data['timestamp'].apply(lambda x: datetime.fromisoformat(x))

# Create a new column called 'year'
data['year'] = data['timestamp'].dt.year

# Create output folder
output_dir = Path('split_by_year')
output_dir.mkdir(parents=True, exist_ok=True)

# Split by year and save as CSV
for year, df_year in data.groupby('year'):
    output_path = output_dir / f'team_1_{year}.csv'
    df_year.drop(columns='year').to_csv(output_path, index=False)
    print(f"Saved {len(df_year)} rows for year {year} → {output_path}")

FileNotFoundError: [Errno 2] No such file or directory: '/content/team_1.parquet'

In [ ]:
# Split by month and save as CSV
for (year, month), df_month in data.groupby(['year', 'month']):
    output_path = output_dir / f'team_1_{year}_{month:02d}.csv'
    df_month.drop(columns=['year', 'month']).to_csv(output_path, index=False)
    print(f"Saved {len(df_month)} rows for {year}-{month:02d} → {output_path}")

Saved 154815 rows for 2024-01 → split_by_year/team_1_2024_01.csv
Saved 145318 rows for 2024-02 → split_by_year/team_1_2024_02.csv
Saved 138619 rows for 2024-03 → split_by_year/team_1_2024_03.csv
Saved 142875 rows for 2024-04 → split_by_year/team_1_2024_04.csv
Saved 152912 rows for 2024-05 → split_by_year/team_1_2024_05.csv
Saved 138910 rows for 2024-06 → split_by_year/team_1_2024_06.csv
Saved 149935 rows for 2024-07 → split_by_year/team_1_2024_07.csv
Saved 146398 rows for 2024-08 → split_by_year/team_1_2024_08.csv
Saved 138737 rows for 2024-09 → split_by_year/team_1_2024_09.csv
Saved 152319 rows for 2024-10 → split_by_year/team_1_2024_10.csv
Saved 149151 rows for 2024-11 → split_by_year/team_1_2024_11.csv
Saved 153696 rows for 2024-12 → split_by_year/team_1_2024_12.csv
Saved 149973 rows for 2025-01 → split_by_year/team_1_2025_01.csv
Saved 132994 rows for 2025-02 → split_by_year/team_1_2025_02.csv
Saved 152788 rows for 2025-03 → split_by_year/team_1_2025_03.csv
Saved 145329 rows for 2025-04 → split_by_year/team_1_2025_04.csv
Saved 148462 rows for 2025-05 → split_by_year/team_1_2025_05.csv
Saved 141251 rows for 2025-06 → split_by_year/team_1_2025_06.csv
Saved 145647 rows for 2025-07 → split_by_year/team_1_2025_07.csv
Saved 143035 rows for 2025-08 → split_by_year/team_1_2025_08.csv
Saved 131304 rows for 2025-09 → split_by_year/team_1_2025_09.csv
Saved 148846 rows for 2025-10 → split_by_year/team_1_2025_10.csv
Saved 145456 rows for 2025-11 → split_by_year/team_1_2025_11.csv
Saved 147189 rows for 2025-12 → split_by_year/team_1_2025_12.csv

In [ ]:
df24 = pd.read_csv('/content/split_by_year/team_1_2024.csv')
df24.head()

,station_id,state,city,station_name,timestamp,datetime,at_c,rh_percent,ws_m_s,wd_deg,...,tot_rf_mm,sr_w_mt2,bp_mmhg,vws_m_s,pollutant,value,station,month,day,hour
0,site_5024,Delhi,Delhi,"Alipur, Delhi - DPCC",2024-01-01 00:00:00+00:00,2024-01-01 00:00:00+00:00,8.2,76.0,NaN,72.9,...,0.0,3.8,973.7,NaN,benzene,2.10,"Alipur, Delhi - DPCC",1,1,0
1,site_301,Delhi,Delhi,"Anand Vihar, Delhi - DPCC",2024-01-01 00:00:00+00:00,2024-01-01 00:00:00+00:00,11.5,80.0,0.3,44.0,...,0.0,5.0,742.0,NaN,no2,45.90,"Anand Vihar, Delhi - DPCC",1,1,0
2,site_1420,Delhi,Delhi,"Ashok Vihar, Delhi - DPCC",2024-01-01 00:00:00+00:00,2024-01-01 00:00:00+00:00,10.9,83.9,1.0,57.7,...,0.0,5.4,983.1,NaN,co,0.90,"Ashok Vihar, Delhi - DPCC",1,1,0
3,site_301,Delhi,Delhi,"Anand Vihar, Delhi - DPCC",2024-01-01 00:00:00+00:00,2024-01-01 00:00:00+00:00,11.5,80.0,0.3,44.0,...,0.0,5.0,742.0,NaN,nh3,18.80,"Anand Vihar, Delhi - DPCC",1,1,0
4,site_301,Delhi,Delhi,"Anand Vihar, Delhi - DPCC",2024-01-01 00:00:00+00:00,2024-01-01 00:00:00+00:00,11.5,80.0,0.3,44.0,...,0.0,5.0,742.0,NaN,co,1.57,"Anand Vihar, Delhi - DPCC",1,1,0

In [ ]:
df25 = pd.read_csv('/content/split_by_year/team_1_2025.csv')
df25.head()

,station_id,state,city,station_name,timestamp,datetime,at_c,rh_percent,ws_m_s,wd_deg,...,tot_rf_mm,sr_w_mt2,bp_mmhg,vws_m_s,pollutant,value,station,month,day,hour
0,site_108,Delhi,Delhi,"Aya Nagar, Delhi - IMD",2025-01-01 00:00:00+00:00,2025-01-01 00:00:00+00:00,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,co,0.99,"Aya Nagar, Delhi - IMD",1,1,0
1,site_108,Delhi,Delhi,"Aya Nagar, Delhi - IMD",2025-01-01 00:00:00+00:00,2025-01-01 00:00:00+00:00,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,pm10,100.50,"Aya Nagar, Delhi - IMD",1,1,0
2,site_108,Delhi,Delhi,"Aya Nagar, Delhi - IMD",2025-01-01 00:00:00+00:00,2025-01-01 00:00:00+00:00,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,ozone,46.12,"Aya Nagar, Delhi - IMD",1,1,0
3,site_108,Delhi,Delhi,"Aya Nagar, Delhi - IMD",2025-01-01 00:00:00+00:00,2025-01-01 00:00:00+00:00,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,no2,20.04,"Aya Nagar, Delhi - IMD",1,1,0
4,site_108,Delhi,Delhi,"Aya Nagar, Delhi - IMD",2025-01-01 00:00:00+00:00,2025-01-01 00:00:00+00:00,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,no,30.36,"Aya Nagar, Delhi - IMD",1,1,0